-- AlterTable
ALTER TABLE "UserProfile" ALTER COLUMN "awards" DROP NOT NULL,
ALTER COLUMN "awards" SET DATA TYPE TEXT,
ALTER COLUMN "languages" DROP NOT NULL,
ALTER COLUMN "languages" SET DATA TYPE TEXT;
